### PR TITLE
Fixed and improved the Preview Tooling for Customizer

### LINKED ISSUE #260: Customizer functionality is broken
The Preview Tools stopped working with WordPress 4.7 and up as the slider does not change width or height of the previewer's iframe.

### PR DESCRIPTION
**Pull request by hellofromtonya**
Closes #260 

As of WordPress 4.7 and up, Bean's Preview Tooling has not worked in Customizer.  We could not change the previewer's width or height.

This PR fixes those issues, while also improving the script to use Weston's preferred approach to binding to Customizer.

- Tested in Chrome, Firefox, and Firefox Dev
- Tested on WordPress 4.1, 4.4 and 4.9.6
- Tested on Mac and Windows.

This PR also adds:

- labels to the activation fields, as it could easily confuse a user as to what they are.  
- descriptions under each grouping.

In doing so, this fixed the jumpy slider when digits were 4 or more.

### CODE REVIEW

File: lib/admin/wp-customize.php [hunk 1]
```diff
@@ -65,12 +68,14 @@ function beans_do_register_wp_customize_options() {
 
 	$fields = array(
 		array(
-			'id'     => 'beans_viewport_width_group',
-			'label'  => __( 'Viewport Width', 'tm-beans' ),
-			'type'   => 'group',
-			'fields' => array(
+			'id'          => 'beans_viewport_width_group',
+			'label'       => __( 'Viewport Width - for Previewing Only', 'tm-beans' ),
+			'description' => __( 'Slide left or right to change the viewport width. Publishing will not change the height of your website.', 'tm-beans' ),
```
Comment (christophherr) [inline lib/admin/wp-customize.php]: width of your website
