### PR TITLE
Fixed whitespace bug in compiler

### LINKED ISSUE #255: Bug - Compiler is removing ALL whitespace from CSS.
The compiler is removing all of the whitespace from the CSS.  That means things like `margin: 0 0 10px 0;` would become `margin:0010px0`;  Whoopsie.  Not what we want.

[The issue is here](https://github.com/Getbeans/Beans/blob/development/lib/api/compiler/class-beans-compiler.php#L794), where I added the bug.

The fix is:

```
	private function strip_whitespace( $content ) {
		$replace = array(
			'#/\*.*?\*/#s' => '', // Strip comments.
			'#\s\s+#'      => ' ', // Strip excess whitespace.
		);

		$search  = array_keys( $replace );
		$content = preg_replace( $search, $replace, $content );

		// Strip all new lines and tabs.
		$content = str_replace( array( "\r\n", "\r", "\n", "\t" ), '', $content );

		$replace = array(
			': '   => ':',
			'; '   => ';',
			' {'   => '{',
			' }'   => '}',
			', '   => ',',
			'{ '   => '{',
			';}'   => '}', // Strip optional semicolons.
			',\n'  => ',', // Don't wrap multiple selectors.
			'\n}'  => '}', // Don't wrap closing braces.
			'}'    => "}\n", // Put each rule on it's own line.
			'\n'   => '', // Remove all line breaks.
			"}\n " => "}\n", // Remove the whitespace at start of each new line.
		);
```

### PR DESCRIPTION
**Pull request by hellofromtonya**
I added a bug back when I did the Compiler.  It stripped out all of the whitespace from the CSS.  So style declarations like:

```
margin: 0 0 10px 0;
```

were converted into:

```
margin:0010px0;
```

Not good.  Doh.

This PR fixes my bug by only removing extra whitespaces.  It also strips the whitespace at the start of each new line.  And it fixes the associated CSS tests.

Closes #255.

### CODE REVIEW

File: lib/api/compiler/class-beans-compiler.php [hunk 1]
```diff
@@ -785,26 +785,28 @@ private function remove_modified_files( $hash, $filemtime_hash ) {
...
+			' {'   => '{',
+			' }'   => '}',
+			', '   => ',',
+			'{ '   => '{',
+			';}'   => '}', // Strip optional semicolons.
+			',\n'  => ',', // Don't wrap multiple selectors.
+			'\n}'  => '}', // Don't wrap closing braces.
+			'}'    => "}\n", // Put each rule on it's own line.
+			'\n'   => '', // Remove all line breaks.
+			"}\n " => "}\n", // Remove the whitespace at start of each new line.
```
Comment (hellofromtonya) [inline lib/api/compiler/class-beans-compiler.php]: NEW: @christophherr I'm adding this pattern (on L809) to remove the extra whitespace at the start of each new line.

File: lib/api/compiler/class-beans-compiler.php [hunk 2]
```diff
@@ -785,26 +785,28 @@ private function remove_modified_files( $hash, $filemtime_hash ) {
...
+			'#\s\s+#'      => ' ', // Strip excess whitespace.
 		);
 
 		$search  = array_keys( $replace );
 		$content = preg_replace( $search, $replace, $content );
 
-		// Strip all new lines, tabs, and whitespace.
-		$content = str_replace( array( "\r\n", "\r", "\n", "\t", ' ' ), '', $content );
+		// Strip all new lines and tabs.
+		$content = str_replace( array( "\r\n", "\r", "\n", "\t" ), '', $content );
```
Comment (hellofromtonya) [inline lib/api/compiler/class-beans-compiler.php]: CHANGED: @christophherr Here, I've removed the space stripper.  This was the buggie.

File: lib/api/compiler/class-beans-compiler.php [hunk 3]
```diff
@@ -785,26 +785,28 @@ private function remove_modified_files( $hash, $filemtime_hash ) {
 	private function strip_whitespace( $content ) {
 		$replace = array(
 			'#/\*.*?\*/#s' => '', // Strip comments.
+			'#\s\s+#'      => ' ', // Strip excess whitespace.
```
Comment (hellofromtonya) [inline lib/api/compiler/class-beans-compiler.php]: PUT BACK: @christophherr This is the original code that strips excess whitespace.

File: tests/phpunit/integration/api/uikit/beans-uikit/compile.php [hunk 4]
```diff
@@ -111,19 +111,27 @@ public function test_should_compile_styles() {
...
+.uk-button-danger:active,.uk-button-danger.uk-active{background-color:#c91032;color:#fff}
+.uk-button:disabled{background-color:#f5f5f5;color:#999}
 EOB;
 		$this->assertContains( $button_css, $compiled_css );
 
 		$overlay_css = <<<EOB
 .uk-overlay{display:inline-block;position:relative;max-width:100%;vertical-align:middle;overflow:hidden;-webkit-transform:translateZ(0);margin:0}
-.uk-overlay.uk-border-circle{-webkit-mask-image:-webkit-radial-gradient(circle,white100%,black100%)}
-.uk-overlay>:first-child{margin-bottom:0}
+.uk-overlay.uk-border-circle{-webkit-mask-image:-webkit-radial-gradient(circle,white 100%,black 100%)}
```
Comment (hellofromtonya) [inline tests/phpunit/integration/api/uikit/beans-uikit/compile.php]: Notice how the CSS declaration has the right spacing again:

Old:

```
-webkit-mask-image:-webkit-radial-gradient(circle,white100%,black100%)
```

New:

```
-webkit-mask-image:-webkit-radial-gradient(circle,white 100%,black 100%)
```
