### PR TITLE
Fixed HTML validator errors

### LINKED ISSUE #217: Audit the use of ARIA roles
The [HTML validator](https://validator.w3.org/nu/) throws some errors and warnings about our use of roles.
e.g.:
html-validator-errors-warnings
 
Related issues from _s:
```
https://github.com/Automattic/_s/issues/1132
https://github.com/Automattic/_s/issues/1202
```

### PR DESCRIPTION
**Pull request by christophherr**
- Wraps post, posts and comment pagination in `<nav>` elements and adds `aria-labels`
- Changes rel="designer" to rel="nofollow" 

closes #217

### CODE REVIEW

File: lib/templates/fragments/comments.php [hunk 1]
```diff
@@ -286,57 +288,67 @@ function beans_comments_navigation() {
...
-			$previous_icon  = beans_open_markup(
-				'beans_previous_icon[_comments_navigation]',
-				'span',
-				array(
-					'class'       => 'uk-icon-angle-double-left uk-margin-small-right',
-					'aria-hidden' => 'true',
-				)
-			);
-			$previous_icon .= beans_close_markup( 'beans_previous_icon[_comments_navigation]', 'span' );
+			// Previous.
```
Comment (hellofromtonya) [inline lib/templates/fragments/comments.php]: Shift the inline comment over one tab to line up with the `if` conditional below.

File: lib/templates/fragments/comments.php [hunk 2]
```diff
@@ -286,57 +288,67 @@ function beans_comments_navigation() {
...
 
-		beans_close_markup_e( 'beans_comments_navigation_item[_previous]', 'li' );
-	}
+			beans_close_markup_e( 'beans_comments_navigation_item[_previous]', 'li' );
+		}
 
-		// Next.
-	if ( get_next_comments_link() ) {
-		beans_open_markup_e( 'beans_comments_navigation_item[_next]', 'li', array( 'class' => 'uk-pagination-next' ) );
+			// Next.
```
Comment (hellofromtonya) [inline lib/templates/fragments/comments.php]: Shift the inline comment over one tab to line up with the `if` conditional below.

File: lib/templates/fragments/menu.php [hunk 3]
```diff
@@ -22,10 +22,11 @@ function beans_primary_menu() {
...
 		array(
-			'class'     => 'tm-primary-menu uk-float-right uk-navbar',
-			'role'      => 'navigation',
-			'itemscope' => 'itemscope',
-			'itemtype'  => 'http://schema.org/SiteNavigationElement',
+			'class'      => 'tm-primary-menu uk-float-right uk-navbar',
+			'role'       => 'navigation',
+			'itemscope'  => 'itemscope',
+			'itemtype'   => 'http://schema.org/SiteNavigationElement',
+			'aria-label' => 'Primary Navigation Menu',
```
Comment (hellofromtonya) [inline lib/templates/fragments/menu.php]: Add internationalization here:

```
__( 'Primary Navigation Menu', 'tm-beans' );
```

File: lib/templates/fragments/menu.php [hunk 4]
```diff
@@ -112,8 +113,9 @@ function beans_primary_offcanvas_menu() {
 		'beans_primary_offcanvas_menu',
 		'nav',
 		array(
-			'class' => 'tm-primary-offcanvas-menu uk-margin uk-margin-top',
-			'role'  => 'navigation',
+			'class'      => 'tm-primary-offcanvas-menu uk-margin uk-margin-top',
+			'role'       => 'navigation',
+			'aria-label' => 'Off-Canvas Primary Navigation Menu',
```
Comment (hellofromtonya) [inline lib/templates/fragments/menu.php]: Add internationalization here:

```
__( 'Off-Canvas Primary Navigation Menu', 'tm-beans' );
```

File: lib/templates/fragments/post.php [hunk 5]
```diff
@@ -534,39 +536,49 @@ function beans_post_navigation() {
...
 	beans_open_markup_e(
-		'beans_post_navigation',
-		'ul',
+		'beans_post_navigation_nav_container',
+		'nav',
 		array(
-			'class' => 'uk-pagination',
-			'role'  => 'navigation',
+			'role'       => 'navigation',
+			'aria-label' => 'Pagination Navigation',
```
Comment (hellofromtonya) [inline lib/templates/fragments/post.php]: Add internationalization here:

```
__( 'Pagination Navigation', 'tm-beans' );
```

File: lib/templates/fragments/post.php [hunk 6]
```diff
@@ -600,146 +612,156 @@ function beans_posts_pagination() {
...
 	beans_open_markup_e(
-		'beans_posts_pagination',
-		'ul',
+		'beans_posts_pagination_nav_container',
+		'nav',
 		array(
-			'class' => 'uk-pagination uk-grid-margin',
-			'role'  => 'navigation',
+			'role'       => 'navigation',
+			'aria-label' => 'Posts Pagination Navigation',
```
Comment (hellofromtonya) [inline lib/templates/fragments/post.php]: Add internationalization here:

```
__( 'Posts Pagination Navigation', 'tm-beans' );
```

File: lib/templates/fragments/comments.php [hunk 7]
```diff
@@ -286,57 +288,67 @@ function beans_comments_navigation() {
...
 	beans_open_markup_e(
-		'beans_comments_navigation',
-		'ul',
+		'beans_comments_navigation_nav_container',
+		'nav',
 		array(
-			'class' => 'uk-pagination',
-			'role'  => 'navigation',
+			'role'       => 'navigation',
+			'aria-label' => 'Comments Pagination Navigation',
```
[the remark this answers is not in the document]
Comment (hellofromtonya) [reply lib/templates/fragments/comments.php]: LOL no worries....got your back.

**Comment by hellofromtonya** [comment]
Thank you for leading the a11y initiative @christophherr!  Excellent work 💯!
