### PR TITLE
Made `_beans_render_action` and `_beans_unique_action_id` compliant

### LINKED ISSUE #78: When passing more than 1 subhook to `_beans_render_action`, the 1st subhook is called 2x
When calling `_beans_render_action();` with more than one subhook, the first subhook is called twice.  That's not the expected behavior.

For example, when calling `_beans_render_action( 'foo[bar][baz]' );`, the call stack is:

1. `do_action( 'foo' );` fires.
2. `do_action( 'foo[bar]' );` fires.
3. `do_action( 'foo[baz]' );` fires.
4. `do_action( 'foo[bar]' );` fires again. <- Whoops, this shouldn't happen.
5. `do_action( 'foo[bar][baz]' );` fires.

In the above example, `do_action( 'foo[bar]' );` fires 2x.  It's happening in the [cascading sub-hooks section](https://github.com/Getbeans/Beans/blob/development/lib/api/actions/functions.php#L576).

## Tests

This test fails as the 1st hook is being called twice and not once:

```
	/**
	 * Test _beans_render_action() renders two levels of sub-hooks,
	 * but the original hook is not rendered.
	 */
	public function test_should_render_two_levels_of_sub_hooks_but_not_original() {
		$stub    = Beans_Api_Actions_Stub::class;
		$hook    = 'foo[bar][baz]';
		$message = 'Called me. ';

		// The root hook renders.
		add_action( 'foo', array( $stub, 'echo_static' ) );
		Actions\expectDone( 'foo' )->once()->whenHappen( array( $stub, 'echo_static' ) );
		$expected = $message;

		// The 1st sub-hook renders.
		add_action( 'foo[bar]', array( $stub, 'echo_static' ) );
		Actions\expectDone( 'foo[bar]' )->once()->whenHappen( array( $stub, 'echo_static' ) );
		$expected .= $message . $message;

		// These hooks will not render as they are not registered.
		Actions\expectDone( 'foo[baz]' )->never();
		Actions\expectDone( 'foo[bar][baz]' )->never();

		// Run the test.
		$this->assertEquals( $expected, _beans_render_action( $hook, $message ) );
	}
```

The results are:

```
1) Beans\Framework\Tests\UnitTests\API\Actions\Tests_BeansRenderAction::test_should_render_two_levels_of_sub_hooks_but_not_original
Mockery\Exception\InvalidCountException: Method do_action_foo_square_bracket_open_bar_square_bracket_close_() from Mockery_0 should be called
 exactly 1 times but called 2 times.

/Users/hellofromtonya/Sites/beansdev/app/public/wp-content/themes/tm-beans/vendor/mockery/mockery/library/Mockery/CountValidator/Exact.php:37
/Users/hellofromtonya/Sites/beansdev/app/public/wp-content/themes/tm-beans/vendor/mockery/mockery/library/Mockery/Expectation.php:298
/Users/hellofromtonya/Sites/beansdev/app/public/wp-content/themes/tm-beans/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:120
/Users/hellofromtonya/Sites/beansdev/app/public/wp-content/themes/tm-beans/vendor/mockery/mockery/library/Mockery/Container.php:297
/Users/hellofromtonya/Sites/beansdev/app/public/wp-content/themes/tm-beans/vendor/mockery/mockery/library/Mockery/Container.php:282
/Users/hellofromtonya/Sites/beansdev/app/public/wp-content/themes/tm-beans/vendor/mockery/mockery/library/Mockery.php:152
/Users/hellofromtonya/Sites/beansdev/app/public/wp-content/themes/tm-beans/vendor/brain/monkey/inc/api.php:38
/Users/hellofromtonya/Sites/beansdev/app/public/wp-content/themes/tm-beans/tests/phpunit/unit-tests/class-test-case.php:50
```

### PR DESCRIPTION
**Pull request by hellofromtonya**
1. Made `_beans_render_action` WPCS compliant
2. Made `_beans_unique_action_id` WPCS compliant
3. Tests for both
4. Fixed #78

### CODE REVIEW

**Comment by hellofromtonya** [comment]
@ThierryA This PR is ready for your review.

In this one, we are targeting 2 functions only in the API Actions.  @n8finch worked with me on this one to fix issue #78.

Tests pass on Mac, Linux, and Windows.

File: lib/api/actions/functions.php [hunk 1]
```diff
@@ -5,9 +5,13 @@
  * While WordPress requires two or three arguments to remove an action, Beans
  * actions can be modified, replaced, removed or reset using only the ID as a reference.
  *
- * @package API\Actions
+ * @package Beans\Framework\API\Actions
+ *
+ * @since   1.5.0
  */
 
+// @codingStandardsIgnoreStart - Skipping over non-compliant code.
```
Comment (ThierryA) [inline lib/api/actions/functions.php]: This should not be added, if code changes, they need to be compliant.

File: lib/api/actions/functions.php [hunk 2]
```diff
@@ -536,76 +540,95 @@ function _beans_add_anonymous_action( $hook, $callback, $priority = 10, $args =
 
 }
 
+// @codingStandardsIgnoreEnd
```
Comment (ThierryA) [inline lib/api/actions/functions.php]: This should not be added, if code changes, they need to be compliant.

File: lib/api/actions/functions.php [hunk 3]
```diff
@@ -536,76 +540,95 @@ function _beans_add_anonymous_action( $hook, $callback, $priority = 10, $args =
...
+
 /**
  * Render action which can therefore be stored in a variable.
  *
- * @ignore
+ * @since 1.5.0
+ * @access private
```
Comment (ThierryA) [inline lib/api/actions/functions.php]: Currently the WP Parser used to automatically generate Getbeans site PHPDoc doesn't support the `@access` tag, only the `@ignore` which we can frequently find in WP core. That said, we can add support for it using the `wp_parser_pre_import_item` filter. @hellofromtonya could you perhaps create a pre-release tasks list and add this to the list?

File: tests/phpunit/unit/api/actions/stubs/class-action-stub.php [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+		// nothing happening here.
+	}
+
+	/**
+	 * Echo what you send me.
+	 *
+	 * @param string|int $message Message to echo.
+	 */
+	public static function echo_static( $message ) {
+		echo $message;   // @codingStandardsIgnoreLine - WordPress.XSS.EscapeOutput.OutputNotEscaped - reason: we are not testing escaping functionality.
```
Comment (ThierryA) [inline tests/phpunit/unit/api/actions/stubs/class-action-stub.php]: Remove extra spaces after `$message;`;

File: tests/phpunit/unit/api/actions/beansUniqueActionId.php [hunk 5]
```diff
@@ -0,0 +1,116 @@
...
+	 * Test _beans_unique_action_id() should convert closure.
+	 */
+	public function test_should_convert_closure() {
+		$closure = function( $dummy_arg ) {
+			return $dummy_arg;
+		};
+
+		$this->assertEquals( spl_object_hash( $closure ), _beans_unique_action_id( $closure ) );
+		$this->assertNotEquals( spl_object_hash( function() {
+			// nothing here.
```
Comment (ThierryA) [inline tests/phpunit/unit/api/actions/beansUniqueActionId.php]: Comment should begin with a capital letter.

File: tests/phpunit/unit/api/actions/stubs/class-action-stub.php [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+ *
+ * @package Beans\Framework\Tests\Unit\API\Actions
+ */
+class Actions_Stub {
+
+	/**
+	 * Dummy static method.
+	 */
+	public static function dummy_static_method() {
+		// nothing happening here.
```
Comment (ThierryA) [inline tests/phpunit/unit/api/actions/stubs/class-action-stub.php]: Comment should begin with a capital letter.

File: tests/phpunit/unit/api/actions/stubs/class-action-stub.php [hunk 7]
```diff
@@ -0,0 +1,41 @@
...
+	}
+
+	/**
+	 * Dummy method.
+	 */
+	public function dummy_method() {
+		// nothing happening here.
```
Comment (ThierryA) [inline tests/phpunit/unit/api/actions/stubs/class-action-stub.php]: Comment should begin with a capital letter.

File: lib/api/actions/functions.php (hunk 1 above)
Comment (hellofromtonya) [reply lib/api/actions/functions.php]: @ThierryA We have to skip over the functions that have not yet been converted and made compliant.  Else, we have to convert the entire file and all of the functions for each and every PR.  The idea is to break up PRs into smaller chunks in order to ease the code review process.

This PR is just for the 2 functions only and _all of the API actions_ functions.

File: lib/api/actions/functions.php (hunk 2 above)
Comment (hellofromtonya) [reply lib/api/actions/functions.php]: @ThierryA See the note above.

File: lib/api/actions/functions.php (hunk 1 above)
Comment (ThierryA) [reply lib/api/actions/functions.php]: The code sniffer only picks up changes, so you shouldn't have to add that if the functions aren't changed.

File: lib/api/actions/functions.php (hunk 3 above)
Comment (hellofromtonya) [reply lib/api/actions/functions.php]: >That said, we can add support for it using the wp_parser_pre_import_item filter. @hellofromtonya could you perhaps create a pre-release tasks list and add this to the list?

Definitely.  Let me open an issue to remind us of this item.  

As we are updating the codebase, I think it's a good idea to mark private functions.  Typically, private functionality is not documented, as they should not be used within the theme or plugins.

Comment (ThierryA) [reply lib/api/actions/functions.php]: Absolutely agree, that said removing the `@ignore` tag removes the flag which currently tell the WP Parser not to add it to the site, hence the need to use the `wp_parser_pre_import_item` to tell the WP Parser to exclude anything with the `@access private` tag instead, otherwise these functions will be added to the site which we don't want.

File: lib/api/actions/functions.php (hunk 1 above)
Comment (hellofromtonya) [reply lib/api/actions/functions.php]: @ThierryA Actually it failed the PHPCS tests, which is why I put those 2 lines in.

File: lib/api/actions/functions.php (hunk 3 above)
Comment (hellofromtonya) [reply lib/api/actions/functions.php]: Done. DocBlocks for private functions now have this format:

```
 * @since 1.5.0
 * @ignore
 * @access private
```

File: lib/api/actions/functions.php (hunk 1 above)
Comment (ThierryA) [reply lib/api/actions/functions.php]: All fixed now, the dev-lib was incorrectly setup to check changed files instead of only patches.
