### PR TITLE
Made _Beans_Image_Editor, beans_edit_image, & beans_get_images_dir WPCS compliant and tested.

### LINKED ISSUE #115: _Beans_Image_Editor fails to bail out and return the original src for ARRAY_A
When an image does not exist, the editor is unable to edit the original image. The expected behavior is to bail out, returning the original image's src in the configured output format.  This works for all of the output formats, expect for `ARRAY_A`.

### PR DESCRIPTION
**Pull request by hellofromtonya**
This PR affects:

- `_Beans_Image_Editor`
- `beans_get_images_dir()`
- `beans_edit_image()`

1. Made WPCS compliant.
2. Added integration and unit tests.
3. Fixed #115.
4. Optimized, meaning the _API runs slightly faster_:
     - When editing an image, improved the execution by 2.158ms.
     - When existing edited image, improved the execution by 0.014ms.
5. Improved documentation.

## Optimization Results - When Editing an Image

**Scenario**: no existing edited image, meaning the functions will edit, create, and store the new edited image file in the `uploads/beans/images` folder.
 
**Impact to execution time**: Improved by 2.158ms on average

```
-------------------------
MICRO PROFILER REPORT:
-------------------------

PHP version:        5.6.20
Sample Size:        1,000 (per function)
Time Increments:    milliseconds, where 1 ms equals 0.001 second.

  --------------------------------   -------------   -------------   -------------
| Name                             | Result        |  Avg Time     | v1.4.0
|                                  | (ms)          |  (ms)         | (ms)
| -------------------------------- | ------------- | ------------- | -------------
| beans_edit_image                 |    -2.157523  |     35.159147 |    37.316670
 --------------------------------   -------------   -------------   -------------

NOTES:

1. The functions were invoked/exercised 1,000 times during this micro profiler process.
2. The 'diff' column = 'time' - 'v1.4.0'.
3. The 'time' column shows the function's average execution time.
4. 'v1.4.0' shows the same micro-profiler run on Beans v1.4.0.
```

BTW Typically, we would want to run 10k cycles.  But in this case, editing is a slower process. I reduced the samples to 1k.

## Optimization Results - When Processing an Existing Edited Image

**Scenario**: the image has already been edited and exists in our cached storage (i.e. in the `uploads/beans/image` folder
 
**Impact to execution time**: Improved by 0.0.14ms on average

```
-------------------------
MICRO PROFILER REPORT:
-------------------------

PHP version:        5.6.20
Sample Size:        10,000 (per function)
Time Increments:    milliseconds, where 1 ms equals 0.001 second.

  --------------------------------   -------------   -------------   -------------
| Name                             | Result        |  Avg Time     | v1.4.0
|                                  | (ms)          |  (ms)         | (ms)
| -------------------------------- | ------------- | ------------- | -------------
| beans_edit_image EXISTING        |    -0.013994  |      0.335003 |      0.348997
 --------------------------------   -------------   -------------   -------------

NOTES:

1. The functions were invoked/exercised 10,000 times during this micro profiler process.
2. The 'diff' column = 'time' - 'v1.4.0'.
3. The 'time' column shows the function's average execution time.
4. 'v1.4.0' shows the same micro-profiler run on Beans v1.4.0.
```

### CODE REVIEW

File: tests/phpunit/integration/api/image/beans-image-editor/run.php [hunk 1]
```diff
@@ -0,0 +1,339 @@
...
+			$editor->run();
+
+			// Run the tests.
+			$this->assertFileExists( $edited_image_src );
+			$this->assertSame( beans_path_to_url( $edited_image_src ), $editor->run() );
+		}
+	}
+
+	/**
+	 * Test run() should edit the existing image, store it in the "rebuilt path", and then return an index array of its
```
Comment (christophherr) [inline tests/phpunit/integration/api/image/beans-image-editor/run.php]: `...return an indexed array...`

File: tests/phpunit/integration/api/image/beans-image-editor/run.php [hunk 2]
```diff
@@ -0,0 +1,339 @@
...
+
+			// Check the edited image's dimensions.
+			list( $width, $height ) = @getimagesize( $edited_image_src ); // @codingStandardsIgnoreLine - Generic.PHP.NoSilencedErrors.Discouraged  This is a valid use case.
+			$this->assertEquals( 800, $width );
+			$this->assertEquals( 420, $height );
+		}
+	}
+
+	/**
+	 * Test beans_edit_image() should return an indexed array with the original src when the image does not exist.
```
Comment (christophherr) [inline tests/phpunit/integration/api/image/beans-image-editor/run.php]: Test run()

File: tests/phpunit/integration/api/image/beans-image-editor/run.php [hunk 3]
```diff
@@ -0,0 +1,339 @@
...
+
+			// Check the edited image's dimensions.
+			list( $width, $height ) = @getimagesize( $edited_image_src ); // @codingStandardsIgnoreLine - Generic.PHP.NoSilencedErrors.Discouraged  This is a valid use case.
+			$this->assertEquals( 400, $width );
+			$this->assertEquals( 210, $height );
+		}
+	}
+
+	/**
+	 * Test beans_edit_image() should return an object with the original src when the image does not exist.
```
Comment (christophherr) [inline tests/phpunit/integration/api/image/beans-image-editor/run.php]: Test run()

File: tests/phpunit/integration/api/image/beans-image-editor/run.php [hunk 4]
```diff
@@ -0,0 +1,339 @@
...
+		$this->assertFileNotExists( $src );
+		$image_info = $editor->run();
+		$this->assertInstanceOf( 'stdClass', $image_info );
+		$this->assertSame( $src, $image_info->src );
+		$this->assertNull( $image_info->width );
+		$this->assertNull( $image_info->height );
+	}
+
+	/**
+	 * Test run() should return return an object when the edited image exists, meaning that it has already been
```
Comment (christophherr) [inline tests/phpunit/integration/api/image/beans-image-editor/run.php]: `..should return an object`

File: tests/phpunit/integration/api/image/beans-image-editor/run.php [hunk 5]
```diff
@@ -0,0 +1,339 @@
...
+
+			// Check the edited image's dimensions.
+			list( $width, $height ) = @getimagesize( $edited_image_src ); // @codingStandardsIgnoreLine - Generic.PHP.NoSilencedErrors.Discouraged  This is a valid use case.
+			$this->assertEquals( 600, $width );
+			$this->assertEquals( 315, $height );
+		}
+	}
+
+	/**
+	 * Test beans_edit_image() should return an array with the original src when the image does not exist.
```
Comment (christophherr) [inline tests/phpunit/integration/api/image/beans-image-editor/run.php]: Test run()

File: tests/phpunit/integration/api/image/beans-image-editor/run.php [hunk 6]
```diff
@@ -0,0 +1,339 @@
...
+				'src'    => $src,
+				'width'  => null,
+				'height' => null,
+			),
+			$editor->run()
+		);
+	}
+
+	/**
+	 * Test run() should return return an associative array when the edited image exists, meaning that it has already
```
Comment (christophherr) [inline tests/phpunit/integration/api/image/beans-image-editor/run.php]: `...should return an associative...`

File: tests/phpunit/integration/api/image/beansEditImage.php [hunk 7]
```diff
@@ -0,0 +1,98 @@
...
+require_once __DIR__ . '/includes/class-image-test-case.php';
+
+/**
+ * Class Tests_BeansEditImage
+ *
+ * @package Beans\Framework\Tests\Integration\API\Image
+ * @group   integration-tests
+ * @group   api
+ */
+class Tests_Beans_Edit_Image extends Image_Test_Case {
```
Comment (christophherr) [inline tests/phpunit/integration/api/image/beansEditImage.php]: Class name in comment and class name "in use" don't match.

File: tests/phpunit/integration/api/image/beansEditImage.php [hunk 8]
```diff
@@ -0,0 +1,98 @@
...
+	 * Set up the test fixture before we start.
+	 */
+	public static function setUpBeforeClass() {
+		parent::setUpBeforeClass();
+
+		static::$fixtures_dir = realpath( __DIR__ . '/../fixtures' );
+	}
+
+	/**
+	 * Test init() should return original src when the image does not exist.
```
Comment (christophherr) [inline tests/phpunit/integration/api/image/beansEditImage.php]: Test beans_edit_image()

File: tests/phpunit/integration/api/image/beansGetImagesDir.php [hunk 9]
```diff
@@ -0,0 +1,49 @@
...
+	 * Test beans_get_images_dir() should return the filtered images' directory.
+	 */
+	public function test_should_return_filtered_images_dir() {
+		Monkey\Functions\expect( 'test_filter_beans_images_dir' )
+			->once()
+			->with( vfsStream::url( 'uploads/beans/images/' ) )
+			->andReturn( 'foo' );
+
+		add_filter( 'beans_images_dir', 'test_filter_beans_images_dir' );
+
```
Comment (christophherr) [inline tests/phpunit/integration/api/image/beansGetImagesDir.php]: // Run the test.

File: tests/phpunit/integration/api/image/beansGetImagesDir.php [hunk 10]
```diff
@@ -0,0 +1,49 @@
...
+		$this->assertSame( 'foo/', beans_get_images_dir() );
+
```
Comment (christophherr) [inline tests/phpunit/integration/api/image/beansGetImagesDir.php]: // Clean up.

File: tests/phpunit/unit/api/image/beans-image-editor/createEditedImage.php [hunk 11]
```diff
@@ -0,0 +1,102 @@
+<?php
+/**
+ * Tests for get_image_info() method of _Beans_Image_Editor.
```
Comment (christophherr) [inline tests/phpunit/unit/api/image/beans-image-editor/createEditedImage.php]: Doesn't match file or class name.

File: tests/phpunit/integration/api/image/beans-image-editor/createEditedImage.php [hunk 12]
```diff
@@ -0,0 +1,87 @@
+<?php
+/**
+ * Tests for get_image_info() method of _Beans_Image_Editor.
```
Comment (christophherr) [inline tests/phpunit/integration/api/image/beans-image-editor/createEditedImage.php]: File name is createEditedImage.php but class name and tested function is get_image_info()
Similar for Unit tests.

File: tests/phpunit/unit/api/image/beans-image-editor/createEditedImage.php [hunk 13]
```diff
@@ -0,0 +1,102 @@
...
+require_once BEANS_TESTS_LIB_DIR . 'api/image/class-beans-image-editor.php';
+
+/**
+ * Class Tests_Beans_Edit_Image_GetImageInfo
+ *
+ * @package Beans\Framework\Tests\Unit\API\Image
+ * @group   unit-tests
+ * @group   api
+ */
+class Tests_Beans_Edit_Image_CreateEditedImage extends Image_Test_Case {
```
Comment (christophherr) [inline tests/phpunit/unit/api/image/beans-image-editor/createEditedImage.php]: Matches file name but not Comment class name or tested function.

File: tests/phpunit/unit/api/image/beans-image-editor/run.php [hunk 14]
```diff
@@ -0,0 +1,399 @@
...
+	 * Set up the test fixture.
+	 */
+	protected function setUp() {
+		parent::setUp();
+
+		Monkey\Functions\when( 'is_main_site' )->justReturn( true );
+	}
+
+	/**
+	 * Test run() should edit the existing image, store it in the "rebuilt path", and then return it's URL.
```
Comment (christophherr) [inline tests/phpunit/unit/api/image/beans-image-editor/run.php]: `...return its URL.`

File: tests/phpunit/unit/api/image/beans-image-editor/run.php [hunk 15]
```diff
@@ -0,0 +1,399 @@
...
+			// Run the tests.
+			$this->assertFileNotExists( $edited_image_src );
+			$image_info = $editor->run();
+			$this->assertFileExists( $edited_image_src );
+			$this->assertSame( beans_path_to_url( $edited_image_src ), $image_info );
+		}
+	}
+
+	/**
+	 * Test init() should return original src when the image does not exist.
```
Comment (christophherr) [inline tests/phpunit/unit/api/image/beans-image-editor/run.php]: Test run() should return the original...

File: tests/phpunit/unit/api/image/beans-image-editor/run.php [hunk 16]
```diff
@@ -0,0 +1,399 @@
...
+	 */
+	public function test_should_return_original_src_when_no_image() {
+		$src    = 'path/does/not/exist/image.jpg';
+		$editor = new _Beans_Image_Editor( $src, array( 'resize' => array( 800, false ) ) );
+
+		// Simulate the WordPress' Editor.
```
Comment (christophherr) [inline tests/phpunit/unit/api/image/beans-image-editor/run.php]: Simulate the WordPress Editor. (I'll ignore them now... promise...)

File: tests/phpunit/unit/api/image/beans-image-editor/run.php [hunk 17]
```diff
@@ -0,0 +1,399 @@
...
+			static::$fixtures_dir . '/image1.jpg',
+			static::$fixtures_dir . '/image2.jpg',
+		);
+		$args          = array( 'resize' => array( 800, false ) );
+
+		foreach ( $image_sources as $src ) {
+			$editor           = new _Beans_Image_Editor( $src, $args );
+			$edited_image_src = $this->init_virtual_image( $rebuilt_path, $editor );
+
+			// Simulate the WordPress' Editor.
```
Comment (christophherr) [inline tests/phpunit/unit/api/image/beans-image-editor/run.php]: Simulate the WordPress Editor.

File: tests/phpunit/unit/api/image/beans-image-editor/createEditedImage.php [hunk 18]
```diff
@@ -0,0 +1,102 @@
...
+	public function test_should_return_false_when_no_image() {
+		$get_image_info = $this->get_reflective_method( 'create_edited_image' );
+		$rebuilt_path   = $this->get_reflective_property();
+		$src            = 'path/does/not/exist/image.jpg';
+		$args           = array( 'resize' => array( 800, false ) );
+
+		$editor           = new _Beans_Image_Editor( $src, $args );
+		$edited_image_src = $this->init_virtual_image( $rebuilt_path, $editor );
+
+		// Simulate the WordPress' Editor.
```
Comment (christophherr) [inline tests/phpunit/unit/api/image/beans-image-editor/createEditedImage.php]: Simulate the WordPress Editor. 
(Not sure if I caught them all. Better run a search & replace)

File: tests/phpunit/unit/api/image/beans-image-editor/run.php [hunk 19]
```diff
@@ -0,0 +1,399 @@
...
+			Monkey\Functions\expect( 'is_wp_error' )->never();
+
+			// Run the tests.
+			$this->assertFileExists( $edited_image_src );
+			$this->assertSame( beans_path_to_url( $edited_image_src ), $editor->run() );
+		}
+	}
+
+	/**
+	 * Test run() should edit the existing image, store it in the "rebuilt path", and then return an index array of its
```
Comment (christophherr) [inline tests/phpunit/unit/api/image/beans-image-editor/run.php]: `... an indexed array...`

File: tests/phpunit/unit/api/image/beans-image-editor/run.php [hunk 20]
```diff
@@ -0,0 +1,399 @@
...
+			// Run the tests.
+			$this->assertFileNotExists( $edited_image_src );
+			$image_info = $editor->run();
+			$this->assertFileExists( $edited_image_src );
+			$this->assertSame( array( beans_path_to_url( $edited_image_src ), 1200, 630 ), $image_info );
+		}
+	}
+
+	/**
+	 * Test beans_edit_image() should return an indexed array with the original src when the image does not exist.
```
Comment (christophherr) [inline tests/phpunit/unit/api/image/beans-image-editor/run.php]: Test run()

File: tests/phpunit/unit/api/image/beans-image-editor/run.php [hunk 21]
```diff
@@ -0,0 +1,399 @@
...
+			$this->assertInstanceOf( 'stdClass', $image_info );
+			$this->assertSame( beans_path_to_url( $edited_image_src ), $image_info->src );
+			$this->assertSame( 1200, $image_info->width );
+			$this->assertSame( 630, $image_info->height );
+			$this->assertFileExists( $edited_image_src );
+		}
+	}
+
+	/**
+	 * Test beans_edit_image() should return an object with the original src when the image does not exist.
```
Comment (christophherr) [inline tests/phpunit/unit/api/image/beans-image-editor/run.php]: Test run()

File: tests/phpunit/unit/api/image/beans-image-editor/run.php [hunk 22]
```diff
@@ -0,0 +1,399 @@
...
+					'width'  => 1200,
+					'height' => 630,
+				),
+				$image_info
+			);
+		}
+	}
+
+	/**
+	 * Test beans_edit_image() should return an associative array with the original src when the image does not exist.
```
Comment (christophherr) [inline tests/phpunit/unit/api/image/beans-image-editor/run.php]: Test run()

File: tests/phpunit/unit/api/image/beans-image-editor/run.php [hunk 23]
```diff
@@ -0,0 +1,399 @@
...
+				'src'    => $src,
+				'width'  => null,
+				'height' => null,
+			),
+			$editor->run()
+		);
+	}
+
+	/**
+	 * Test run() should return return an associative array when the edited image exists, meaning that it has already
```
Comment (christophherr) [inline tests/phpunit/unit/api/image/beans-image-editor/run.php]: ... should return an ..

File: tests/phpunit/unit/api/image/beansEditImage.php [hunk 24]
```diff
@@ -0,0 +1,119 @@
...
+
+		static::$fixtures_dir = realpath( __DIR__ . '/../fixtures' );
+
+		if ( ! defined( 'BEANS_API_PATH' ) ) {
+			define( 'BEANS_API_PATH', BEANS_TESTS_LIB_DIR . 'api/' );
+		}
+	}
+
+	/**
+	 * Test init() should return original src when the image does not exist.
```
Comment (christophherr) [inline tests/phpunit/unit/api/image/beansEditImage.php]: Test beans_edit_image()
